export const LABEL_COLORS = [
  { value: "#b8255f", label: "Berry Red" },
  { value: "red", label: "Red" },
  { value: "orange", label: "Orange" },
  { value: "gold", label: "Gold" },
  { value: "#afb83b", label: "Olive Green" },
  { value: "limeGreen", label: "Lime Green" },
  { value: "green", label: "Green" },
  { value: "#6accbc", label: "Mint Green" },
  { value: "teal", label: "Teal" },
  { value: "skyBlue", label: "Sky Blue" },
  { value: "lightBlue", label: "Light Blue" },
  { value: "blue", label: "Blue" },
  { value: "#884dff", label: "Grape" },
  { value: "violet", label: "Violet" },
  { value: "lavender", label: "Lavender" },
  { value: "magenta", label: "Magenta" },
  { value: "salmon", label: "Salmon" },
  { value: "#808080", label: "Charcoal" },
  { value: "grey", label: "Grey" },
  { value: "#ccac93", label: "Taupe" },
];
