/**
 * It is ids of the popup menu items that will be passed as an argument
 * to a click handler when the menu item is clicked.
 */
export const actionIds = {
  ADD_PROJECT_ABOVE: "ADD_PROJECT_ABOVE",
  ADD_PROJECT_BELOW: "ADD_PROJECT_BELOW",
  EDIT_PROJECT: "EDIT_PROJECT",
  ADD_PROJECT_TO_FAVORITES: "ADD_PROJECT_TO_FAVORITES",
  REMOVE_PROJECT_FROM_FAVORITES: "REMOVE_PROJECT_FROM_FAVORITES",
  DELETE_PROJECT: "DELETE_PROJECT",

  ADD_LABEL_ABOVE: "ADD_LABEL_ABOVE",
  ADD_LABEL_BELOW: "ADD_LABEL_BELOW",
  EDIT_LABEL: "EDIT_LABEL",
  ADD_LABEL_TO_FAVORITES: "ADD_LABEL_TO_FAVORITES",
  REMOVE_LABEL_FROM_FAVORITES: "REMOVE_LABEL_FROM_FAVORITES",
  DELETE_LABEL: "DELETE_LABEL",
} as const;
